pipeline:
  run-tests:
    image: node:10.12.0
    commands:
      - chmod +x ./bin/drone-tests.sh
      - ./bin/drone-tests.sh
    when:
      status: [ failure, success ]
      event: [ pull_request, push ]