version: '3.6'  
services:
  landing:
    build:
      context: "./"
      dockerfile: Dockerfile.dev
    networks:
      - auxilin
    environment:
      NODE_ENV: development
    volumes:
      - "./src:/app/src"
    ports:
      - "3000:3000"

networks:
  auxilin:
    name: auxilin_network
